apiVersion: batch/v1
kind: Job
metadata:
  name: <job-name>
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox 
        command: 
          - /bin/sh
          - -c
          - date; echo Hello from the Kubernetes cluster
      restartPolicy: Never
#  backoffLimit: 4